### ISSUE TITLE
克隆到本地问题

### ISSUE THREAD

**Issue by mjyy22** [OpenHUTB/hutb#121]
![1725624326206](https://github.com/user-attachments/assets/c9ad071c-c85b-484d-9f1c-29fb6b4c50f5)

git clone 到本地后文件夹出现在桌面就马上消失

**Comment by Muyunshui** [comment]
在你需要把仓库文件克隆到的文件夹里打开终端窗口，再进行克隆操作试一试

**Comment by Muyunshui** [comment]
不要直接在桌面里克隆

**Comment by 52Herze** [comment]
在文件夹里可以，试过了
