### ISSUE TITLE
贡献为什么都归到一个requests里了

### ISSUE THREAD

**Issue by zhemuqi** [OpenHUTB/hutb#2031]
![屏幕截图 2024-12-20 155830](https://github.com/user-attachments/assets/d90b309f-348a-44f2-9455-ab9197966f7c)
就像上面这图，怎么才可以把每次新的注释放到新的请求里。
如果都归到一个里面，会影响给分吗？

**Comment by zero141271** [comment]
不会，给分是看修改的行数，两个数加起来
![Uploading 2024-12-20 (1).png…]()

**Comment by zero141271** [comment]
不会，给分是看修改的行数，两个数加起来
![2024-12-20 (1)](https://github.com/user-attachments/assets/823d798f-8543-4ee9-a286-5a25f57440d8)
