### ISSUE TITLE
VS2019问题

### ISSUE THREAD

**Issue by jun-72** [OpenHUTB/hutb#230]
如图 我这里打开的是sizeof.cpp文件 为什么在执行的时候他总是执行归并排序.cpp文件？
![image](https://github.com/user-attachments/assets/c08e6614-8882-45e1-b1c4-4060a41a8d5b)

**Comment by donghaiwang** [comment]
问问题时要让大家能够复现，比如上传所有源代码或者整个工程。
是不是归并排序.cpp里也有main函数

**Comment by jun-72** [comment]
![image](https://github.com/user-attachments/assets/2a84a16e-68a8-4e91-a07b-484aab794ea7)
![image](https://github.com/user-attachments/assets/56224f4c-3fc2-48ec-8aa6-e2cc2ad30a8a)
只有两个cpp文件有主函数

**Comment by donghaiwang** [comment]
编译器提示tmp变量确实没有定义

**Comment by jun-72** [comment]
我知道tmp报错了  但是我只是想编译并运行siziof.cpp这个文件 那一份排序我还没写完

**Comment by donghaiwang** [comment]
> 我知道tmp报错了 但是我只是想编译并运行siziof.cpp这个文件 那一份排序我还没写完

那就先把保存的文件全注释掉，不然vs会编译其他文件就会编译失败

**Comment by jun-72** [comment]
谢谢老师
