### ISSUE TITLE
数组大小问题

### ISSUE THREAD

**Issue by jun-72** [OpenHUTB/hutb#238]
既然数组名表示首元素的地址 那为什么a和&a[0]大小不一样啊
![image](https://github.com/user-attachments/assets/27003f93-21c9-4349-958c-b63271e6724a)

**Comment by donghaiwang** [comment]
这显示的是a[0]而不是&a[0]

需要看sizeof是怎么实现的，a代表的就是整个数组，输出16；a[0]代表第一个元素1，大小是4字节都没问题。

你想要知道的估计是这个： 
printf("0x%X 0x%X\n", a, &(a[0]));

**Comment by jun-72** [comment]
1. 对 &a[0]和&a为什么大小不一样？

**Comment by jun-72** [comment]
a如果代表的是整个数组 那&a是什么？

**Comment by donghaiwang** [comment]
> a如果代表的是整个数组 那&a是什么？

本质上 `a`、  `&a`  、  `&(a[0])` 没有区别，都是第一个元素的第一个字节的内存单元格地址，就看操作符或函数怎么来解析了。

printf("0x%X 0x%X 0x%X\n", a, &(a[0]), &a);

**Comment by donghaiwang** [comment]
> 1. 对 &a[0]和&a为什么大小不一样？

如果使用sizeof，同一个程序肯定是一样的：

printf("%d %d\n", sizeof(&(a[0])), sizeof(&a));

比如64位程序打印出来是8字节，表示一个指针所占用的内存空间都是64比特。（32位程序打印的是4）

**Comment by jun-72** [comment]
谢谢老师
