### ISSUE TITLE
时间复杂度

### ISSUE THREAD

**Issue by jun-72** [OpenHUTB/hutb#249]
这个代码的时间复杂度怎么算的啊？
![image](https://github.com/user-attachments/assets/f4dfdea0-a111-4ce8-84c8-1f4482763db9)

**Comment by Hyz12345678** [comment]
外层循环有n次，内层循环受外层循环的影响，例如：i=1时，内层循环为n次。内层迭代次数为n/i的和，其中i=1,2,3...n可将其看成调和级数再乘一个n，而调和级数是发散的，所以只能求出近似值，如果将所有项看成是n，就可以求出和为n^2，由于这种假设，可以将n^2看成最坏环境下的时间复杂度，最好情况不知道怎么办了

**Comment by jun-72** [comment]
> 外层循环有n次，内层循环受外层循环的影响，例如：i=1时，内层循环为n次。内层迭代次数为n/i的和，其中i=1,2,3...n可将其看成调和级数再乘一个n，而调和级数是发散的，所以只能求出近似值，如果将所有项看成是n，就可以求出和为n^2，由于这种假设，可以将n^2看成最坏环境下的时间复杂度，最好情况不知道怎么办了

当i=1的时候 确实是调和级数 那当i越来越接近于n的时候 下面那个for循环也会只执行2两次，那为什么是调和级数*n呢

**Comment by donghaiwang** [comment]
内层循环错了，想表达的是 `j <= n / i`吧

**Comment by jun-72** [comment]
> 内层循环错了，想表达的是 `j <= n / i`吧

是的是的 因为我是从伪代码看过来的

**Comment by jun-72** [comment]
改了下
