### ISSUE TITLE
为什么刚拉起请求，请求就被关闭了，求

### ISSUE THREAD

**Issue by smile947** [OpenHUTB/hutb#340]
![微信图片_20240918211938](https://github.com/user-attachments/assets/a324c6f1-c15f-4a39-bd02-7b79b6440d7e)

**Comment by donghaiwang** [comment]
发链接

**Comment by smile947** [comment]
> 发链接
https://github.com/OpenHUTB/carla_cpp/pull/339

**Comment by donghaiwang** [comment]
显示的记录是你手动关闭了，可能点错了？

**Comment by smile947** [comment]
> 显示的记录是你手动关闭了，可能点错了？

好哒，谢谢老师
