### ISSUE TITLE
没有推送权限

### ISSUE THREAD

**Issue by bin562** [OpenHUTB/hutb#6]

**Comment by donghaiwang** [comment]
发下截图

**Comment by bin562** [comment]
![image](https://github.com/user-attachments/assets/d15ca1f4-0587-499a-9fc1-68fb9cc09936)
您好，请问是推送失败的截图吗？还需要别的截图吗

**Comment by donghaiwang** [comment]
参照 [贡献指南](https://github.com/OpenHUTB/PFC/blob/main/CONTRIBUTING.md) 中的 [提交Pull Request](https://zhuanlan.zhihu.com/p/153381521) 中的操作流程。 需要先把 [湖工商的仓库](https://github.com/OpenHUTB/carla_cpp) fork 到自己仓库，先把修改的内容push到自己的仓库，然后再提交 Pull Request 尝试 merge 到湖工商仓库，管理员同意后才可以合并到湖工商仓库。

**Comment by bin562** [comment]
好的
