### ISSUE TITLE
在小乌龟软件中设置了代理还是克隆不了

### ISSUE THREAD

**Issue by ZH1024-Heng** [OpenHUTB/hutb#797]
![屏幕截图 2024-10-18 094741](https://github.com/user-attachments/assets/fde62c57-dd14-4bbe-8523-757ca7ec2750)

**Comment by ZH1024-Heng** [comment]
![Uploading 屏幕截图 2024-10-17 205330.png…]()

**Comment by donghaiwang** [comment]
![image](https://github.com/user-attachments/assets/2bf2b04d-6f8e-4383-8c57-da58e7ce4c5a)
看下这两个端口是不是一致的

**Comment by wangzi-hub** [comment]
直接开个加速器吧

**Comment by wangzi-hub** [comment]
或者转用git

**Comment by ZH1024-Heng** [comment]
搞定了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月11日(周三) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OpenHUTB/carla_cpp] 在小乌龟软件中设置了代理还是克隆不了 (Issue #797)




 
或者转用git

**Comment by wangzi-hub** [comment]
好滴，问题解决了可以关闭一下哦
