### ISSUE TITLE
clone本地问题

### ISSUE THREAD

**Issue by 52Herze** [OpenHUTB/hutb#89]
<img width="441" alt="联想截图_20240905170102" src="https://github.com/user-attachments/assets/a6f8c77d-2514-41d5-a951-fae0cdabd6a0">

这种如何解决

**Comment by Yuuydz** [comment]
你clone打成close了

**Comment by 52Herze** [comment]
> 你clone打成close了
<img width="441" alt="联想截图_20240905170102" src="https://github.com/user-attachments/assets/9d2a21e3-0a18-4ef7-b45d-168b0b08b2d8">
